pipeline:

  publish:
    image: plugins/docker
    tags: latest
    registry: ${DOCKER_REGISTRY_HOST}
    username: ${DOCKER_REGISTRY_USERNAME}
    password: ${DOCKER_REGISTRY_PASSWORD}
    repo: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_NAMESPACE}/${DRONE_REPO_NAME}
    pull_image: false
    when:
      branch:
        - master

  deploy:
    image: peloton/drone-rancher
    url: ${RANCHER_URL}
    access_key: ${RANCHER_ACCESS_KEY}
    secret_key: ${RANCHER_SECRET_KEY}
    service: dev-apps/ci-setup-payload
    docker_image: ${DOCKER_REGISTRY_HOST}/${DOCKER_REGISTRY_NAMESPACE}/${DRONE_REPO_NAME}
    start_first: true
    confirm: true
    timeout: 180
    when:
      branch:
        - master
